config/routes.rb
Rubyfuza::Application.routes.draw do
  get "followings/create"

  resources :chirps do
    collection do
      get 'search'
      get 'user'
    end
  end
  resources :users
  resource :followings

  root :to => 'chirps#index'

end

app/models/chirp.rb
class Chirp < ActiveRecord::Base
  belongs_to :user

  attr_accessor :user_name
  attr_accessible :content, :user_id, :user_name
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user
  belongs_to :following_user, :class_name => "User"

  attr_accessible :following_user

  def self.followers_for_user(user)
    where(:following_user_id => user.id).includes(:user).map(&:user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :login, :name

  has_many :chirps
  has_many :followings

  def followers
    Following.followers_for_user(self)
  end

  def following
    followings.includes(:following_user).map(&:following_user)
  end

  def follow(another_user)
    followings.create(:following_user => another_user)
  end

  def relevant_chirps
    chirps.to_a.concat(following.map(&:chirps).flatten).sort_by do |chirp|
      chirp.created_at
    end.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  # GET /chirps
  # GET /chirps.json
  def index
    @chirps = Chirp.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chirps }
    end
  end

  def user
    @user = User.find_by_name!(params[:name])
    @chirps = @user.relevant_chirps

    respond_to do |format|
      format.html
      format.json { render :json => { :hash => @chirps.hash.to_s }}
    end
  end

  # POST /chirps
  # POST /chirps.json
  def create
    @chirp = ChirpCreationService.new.create(params[:chirp])

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to '/', notice: 'Chirp was successfully created.' }
        format.json { render json: @chirp, status: :created, location: @chirp }
      else
        format.html { render action: "new" }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /search
  # GET /search.json
  def search
    @query = params[:query]
    sql = "content LIKE ?"
    @chirps = Chirp.where([sql, "%#{@query}%"])

    respond_to do |format|
      format.html 
      format.json { render json: @chirps }
    end
  end

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @user = User.find_or_create_by_name!(params[:user])
    @follower = User.find_or_create_by_name!(params[:follower])
    @follower.follow(@user)
    redirect_to user_chirps_path(:name => @user.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Send welcome email
        UserMailer.welcome_email(@user).deliver

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chirps/_chirp.html.haml
.chirp
  = link_to "@#{chirp.user.name}", user_chirps_path(:name => chirp.user.name)
  = chirp.content
  %small.pull-right
    = time_ago_in_words(chirp.created_at)
    ago

app/views/chirps/_form.html.haml
= form_for @chirp do |f|
  - if @chirp.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chirp.errors.count, "error")} prohibited this chirp from being saved:"
      %ul
        - @chirp.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_name
    = f.text_field :user_name
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/chirps/_header.html.haml
%form.form-inline.well(action='/chirps' method='POST')
  .input-prepend
    %span.add-on @
    %input(type='text' name='chirp[user_name]' placeholder='handle')
  %input(type='text' name='chirp[content]' placeholder='Say something!')
  %input(type='submit' value='Chirp your mates')

app/views/chirps/_list.html.haml
%ul.chirps
- @chirps.each do |chirp|
  - if chirp.user
    = render :partial => 'chirp', :locals => { :chirp => chirp }

app/views/chirps/_watcher.html.haml
%div.alert{:id => 'new-chirps-available'}
  There are new chirps available
  %a refresh now

:javascript
  chirpWatcher.boot("#{user_chirps_path(:name => @user.name)}", "#{@chirps.to_a.hash}")

app/views/chirps/edit.html.haml
%h1 Editing chirp

= render 'form'

= link_to 'Show', @chirp
\|
= link_to 'Back', chirps_path

app/views/chirps/index.html.haml
= render "chirps/header"
= render "chirps/list"

app/views/chirps/new.html.haml
%h1 New chirp

= render 'form'

= link_to 'Back', chirps_path

app/views/chirps/search.html.haml
%h1= "Search results: #{@query}"

%ul.chirps
- @chirps.each do |chirp|
  = render :partial => 'chirp', :locals => { :chirp => chirp }

app/views/chirps/show.html.haml
%p#notice= notice

%p
  %b User:
  = @chirp.user
%p
  %b Content:
  = @chirp.content

= link_to 'Edit', edit_chirp_path(@chirp)
\|
= link_to 'Back', chirps_path

app/views/chirps/user.html.haml
= render "chirps/watcher"
= render "chirps/header"

%h4
  Chirps by
  %span.user
    = "@#{@user.name}"
  and
  = pluralize @user.followers.count, "follower"

%form.form-inline.well(action='/followings' method='POST')
  = hidden_field_tag "user", @user.name
  %label <label>Add a follower</label>
  .input-prepend
    %span.add-on @
    %input(type='text' name='follower' data-provide='typeahead')

= render "chirps/list"

app/views/layouts/_navbar.html.haml
.navbar
  .navbar-inner
    %a.brand(href="#") Chirps!
    
    %form.form-search.navbar-form.pull-right{:action => "/chirps/search", :method => "get", :class => "form-search" }
      %input{:type => "search", :name => "query", :class => "search-query" }
      - # %input{:type => "submit", :value => "Search", :class => "btn" }

app/views/layouts/application.html.haml
!!! 5
%head
  %title Rubyfuza Chirps!
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .container
    = render "layouts/navbar"
    = yield

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :login
    = f.text_field :login
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th Login
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= user.login
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Login:
  = @user.login

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path